language: python
python:
  - "3.4"
env:
  - NLTK_DATA=`pwd`
services:
  - redis-server
install:
  - pip install -r requirements.txt
  - python -m nltk.downloader -d . all
  - cp opencricket/config/config.ci.py opencricket/config/config.py
script: python3 ci_build.py
